name: Publish Release

on:
  workflow_dispatch:
  # push:
  #   branches: [ master ]
  #   paths-ignore:
  #     - .github/workflows/*
  #     - '**.md'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      zip_file_name: 'Flow.Launcher.Plugin.DateCalculator.zip'

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'plugin.json'
          prop_path: 'Version'
      - run: echo version ${{steps.version.outputs.prop}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t ./lib
          ls -l
          zip -r ${{env.zip_file_name}} . -x '*.git*'
      - name: Publish
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: ${{env.zip_file_name}}
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}